### ISSUE TITLE
Issue running train.py with parameters

### ISSUE THREAD

**Issue by glestel** [Antimalweb/URLNet#1]
Hello and thanks for the work

I'm trying to run your model on my dataset but I'm having some parameters issues.
The script is not accepting the `--FILTER_SIZE 3,4,5,6 ` : 
``` 
/home/user/URLNet/netenv/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "train.py", line 33, in <module>
    FLAGS._parse_flags() 
  File "/home/user/URLNet/netenv/local/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "/home/user/URLNet/netenv/local/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 630, in __call__
    name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'FILTER_SIZE'. Did you mean: FILTER_SIZES ?
```
And if I user FILTER_SIZES as suggested, I get another issue : 
```
/home/user/URLNet/netenv/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "train.py", line 33, in <module>
    FLAGS._parse_flags() 
  File "/home/user/URLNet/netenv/local/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "/home/user/URLNet/netenv/local/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 470, in __getattr__
    raise AttributeError(name)
AttributeError: _parse_flags
```
The train command is extracted from the `test.sh` and I get similar issues : 
```
#!/usr/bin/env bash

python train.py --FILE_DIR dataset_train.txt \
--DEV_PERCENTAGE 0.001 \
--EMB_MODE 3 --DELIMIT_MODE 1 \
--EMB_DIM 32 --MIN_WORD_FREQ 1 \
--FILTER_SIZES 3,4,5,6 \
--NB_EPOCHS 5 --BATCH_SIZE 1048 --PRINT_EVERY 50 --EVAL_EVERY 500 --CHECKPOINT_EVERY 500 \
--OUTPUT_DIR runs/emb3_dlm1_32dim_minwf1_1conv3456_ep/
```

In addition to the requirement from README, I also installed `libhdf5-7` on the system, and pip packages `h5py scipy`, here is the content of my virtualenv : 
```
$ pip freeze
absl-py==0.1.10
backports.weakref==1.0.post1
bleach==1.5.0
enum34==1.1.6
funcsigs==1.0.2
futures==3.2.0
h5py==2.7.1
html5lib==0.9999999
Markdown==2.6.11
mock==2.0.0
numpy==1.14.0
pbr==3.1.1
Pillow==5.0.0
protobuf==3.5.1
scipy==1.0.0
six==1.11.0
tensorflow==1.5.0
tensorflow-tensorboard==1.5.1
tflearn==0.3.2
Werkzeug==0.14.1
```

Thanks for your help

**Comment by henryhungle** [comment]
Hi @glestel, sorry there was a typo in the run.sh file and in our README writeup. The correct parameter name should be `FILTER_SIZES.` We will update the files accordingly. 
Did you try running the command again? I copied your below command and the program run fine. 

```
#!/usr/bin/env bash

python train.py --FILE_DIR dataset_train.txt \
--DEV_PERCENTAGE 0.001 \
--EMB_MODE 3 --DELIMIT_MODE 1 \
--EMB_DIM 32 --MIN_WORD_FREQ 1 \
--FILTER_SIZES 3,4,5,6 \
--NB_EPOCHS 5 --BATCH_SIZE 1048 --PRINT_EVERY 50 --EVAL_EVERY 500 --CHECKPOINT_EVERY 500 \
--OUTPUT_DIR runs/emb3_dlm1_32dim_minwf1_1conv3456_ep/
```
